spring:
  application:
    name: cloud-shell-task
server:
  port: 7172
  servlet:
    context-path: /cloud-shell-task

system:
  id: "${REALM:browser-task}"
  profile-table-url: "${PROFILE_TABLE_URL:https://api.moonpet.vn/public/api/dynamic/table/profile_manager}"
  cmd: "${CMD:whoami}"