spring:
  application:
    name: cloud-shell-task
server:
  port: 7172
  servlet:
    context-path: /cloud-shell-task

system:
  id: "${REALM:browser-task}"
  profile-table-url: "${PROFILE_TABLE_URL:link connect to profile_manager table}"
  cmd: "${CMD:whoami}"