spring:
  application:
    name: cloud-shell-task
server:
  port: 7172
  servlet:
    context-path: /cloud-shell-task

system:
  id: "${REALM:browser-task}"
  database-json-url: "${DATABASE_JSON_URL:***onpet.vn/public/api/dynamic/table}"
  cmd: "${CMD:whoami}"
  headless-mode: "${HEADLESS_MODE:false}"

github:
  api-url: "${GITHUB_API_URL:https://api.github.com/repos/{{owner}}/{{repo_name}}/contents}"
  token: "${GITHUB_TOKEN: your github token}"

profile-folder:
  user-profile: "${CLOUD_SHELL_CHROME_PROFILE_FOLDER:chrome-profiles-download-extract}"
  user-profile-download: "${CLOUD_SHELL_CHROME_PROFILE_DOWNLOAD_FOLDER:chrome-profiles-download}"

logging:
  file:
    name: log/cloud-shell-task.log
  logback:
    rollingpolicy:
      max-history: 2
